# Generated by Django 5.1.6 on 2025-05-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_evaluation_delete_siterating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattempt',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
