# Generated by Django 5.1.6 on 2025-05-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userattempt_notes_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattempt',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
